### ISSUE TITLE
Create an index page to demonstrate GitHub Pages

### ISSUE THREAD

**Issue by praveenscience** [stjosephs-praveen-livestream/my-first-repo#9]
This might help, if you are creating a website for yourself.

**Comment by stjosephs-praveen-livestream** [comment]
Go ahead and start doing it.

**Comment by xxpsynagure** [comment]
Pragnya Nagure
BE in Computer Science Engineering - Third year
St Joseph Engineering College, Mangalore

LinkedIn : https://www.linkedin.com/in/pragnya-nagure-648458225/
GitHub: https://github.com/xxpsynagure

I'm interested in Full stack and Game Development.
My preferred languages include C++ and Python.
Currently learning and working with the Django Framework and SFML libraries for game dev.
